spring:
    application:
        name: shoe-service

server:
    port: 22222
    context-path: #/walton/

#eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11112/eureka/

druid:
    url: jdbc:mysql://localhost:3306/xx?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driverClass: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 1
    maxActive: 20
    testOnBorrow: true

mybatis:
    typeAliasesPackage: com.shoe.model
    mapperLocations: classpath:mybatis/mapper/*.xml
    configLocation: classpath:mybatis/mybatis-config.xml
    #typeHandlersPackage：扫描typeHandlers的包
    #checkConfigLocation：检查配置文件是否存在
    #executorType：设置执行模式（SIMPLE, REUSE, BATCH），默认为SIMPLE
mapper:
    mappers: com.util.BaseMapper
    not-empty: false
    identity: MYSQL
