FROM docker.zifang.com/centos7-base
MAINTAINER chicol "chicol@yeah.net"

# copy install package files from localhost.
FROM centos7
MAINTAINER chicol "liuwc121709@sina.com"

RUN echo "add group and user"
RUN groupadd mysql  && \
    useradd -r -g mysql mysql

RUN echo "mkdir /usr/local/software folder"
RUN mkdir /usr/local/software

RUN echo "unstall mariadb,mysql"
RUN rpm -qa | grep mariadb | xargs -t -i rpm -e {} --nodeps && \
    rpm -qa | grep mysql | xargs -t -i rpm -e {} --nodeps

RUN echo "download and tar mysql-5.7.18-linux-glibc2.5-x86_64 file"
RUN wget -O /usr/local/software/mysql-5.7.18-linux-glibc2.5-x86_64.tar.gz \
	https://cdn.mysql.com//Downloads/MySQL-5.7/mysql-5.7.18-linux-glibc2.5-x86_64.tar.gz && \
    tar -xzvf mysql-5.7.18-linux-glibc2.5-x86_64.tar.gz

RUN echo "install mysql(mommon,libs,client,server)"
RUN rpm -ivh /usr/local/software/mysql-community-common-5.7.18-linux-glibc2.5-x86_64.rpm && \
    rpm -ivh /usr/local/software/mysql-community-libs-5.7.18-linux-glibc2.5-x86_64.rpm   && \
    rpm -ivh /usr/local/software/mysql-community-client-5.7.18-linux-glibc2.5-x86_64.rpm && \
    rpm -ivh /usr/local/software/mysql-community-server-5.7.18-linux-glibc2.5-x86_64.rpm
   

# Config & Start mysql
RUN echo "user=mysql" >> /etc/my.cnf    && \
    mysqld --initialize                
RUN chown -R mysql:mysql /var/lib/mysql && \
    /usr/sbin/mysqld --daemonize --pid-file=/var/run/mysqld/mysqld.pid

RUN echo "delete software files"
RUN rm -rf /usr/local/software/*
